# Generated by Django 5.2 on 2025-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_estoque', models.PositiveIntegerField()),
                ('marca', models.CharField(max_length=16)),
                ('sku', models.CharField(editable=False, max_length=20, unique=True)),
            ],
        ),
    ]
