# Generated by Django 5.2 on 2025-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
